-- Private tenant template. Apply only through app.tenancy.migrations.
CREATE TABLE {documents}.authentication_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    telegram_id bigint,
    department_id character varying(128)
);
CREATE SEQUENCE {documents}.authentication_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE {documents}.authentication_user_id_seq OWNED BY {documents}.authentication_user.id;
CREATE TABLE {documents}.departments (
    name character varying(128) NOT NULL,
    iiko_id uuid,
    iiko_name character varying(128)
);
CREATE VIEW {documents}.portal_access WITH (security_invoker='true', security_barrier='true') AS
 SELECT id,
    active,
    to_jsonb(sections) AS sections,
    is_portal_admin
   FROM {analytics}.web_users;
CREATE TABLE {documents}.portal_documents_accessevent (
    id bigint NOT NULL,
    actor_supabase_id uuid NOT NULL,
    revision integer NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT portal_documents_accessevent_revision_check CHECK ((revision >= 0))
);
ALTER TABLE {documents}.portal_documents_accessevent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME {documents}.portal_documents_accessevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE {documents}.portal_documents_event (
    id bigint NOT NULL,
    kind character varying(8) NOT NULL,
    document_id bigint NOT NULL,
    version integer NOT NULL,
    action character varying(32) NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    actor_id bigint NOT NULL,
    CONSTRAINT portal_documents_event_version_check CHECK ((version >= 0))
);
ALTER TABLE {documents}.portal_documents_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME {documents}.portal_documents_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE {documents}.portal_documents_grant (
    id bigint NOT NULL,
    kind character varying(8) NOT NULL,
    actions jsonb NOT NULL,
    store_id uuid NOT NULL,
    user_id bigint NOT NULL
);
ALTER TABLE {documents}.portal_documents_grant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME {documents}.portal_documents_grant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE {documents}.portal_documents_notification (
    id bigint NOT NULL,
    kind character varying(8) NOT NULL,
    document_id bigint NOT NULL,
    version integer NOT NULL,
    state character varying(16) NOT NULL,
    attempts integer NOT NULL,
    message_id bigint,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    recipient_id bigint NOT NULL,
    CONSTRAINT portal_documents_notification_attempts_check CHECK ((attempts >= 0)),
    CONSTRAINT portal_documents_notification_version_check CHECK ((version >= 0))
);
ALTER TABLE {documents}.portal_documents_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME {documents}.portal_documents_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE {documents}.portal_documents_operation (
    id uuid NOT NULL,
    kind character varying(8) NOT NULL,
    document_id bigint,
    action character varying(16) NOT NULL,
    fingerprint character varying(64) NOT NULL,
    state character varying(16) NOT NULL,
    result jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    actor_id bigint NOT NULL
);
CREATE TABLE {documents}.portal_documents_userlink (
    id bigint NOT NULL,
    supabase_id uuid,
    revision integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT portal_documents_userlink_revision_check CHECK ((revision >= 0))
);
ALTER TABLE {documents}.portal_documents_userlink ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME {documents}.portal_documents_userlink_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE {documents}.stores (
    id uuid NOT NULL,
    name character varying(128) NOT NULL
);
CREATE TABLE {documents}.waybills (
    id bigint NOT NULL,
    comment text,
    status character varying(16) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    counteragent_id uuid NOT NULL,
    created_by_id bigint NOT NULL,
    processed_by_id bigint,
    store_id uuid NOT NULL,
    processed_at timestamp with time zone,
    submission_state character varying(16) NOT NULL,
    version integer NOT NULL,
    CONSTRAINT waybills_version_check CHECK ((version >= 0))
);
CREATE SEQUENCE {documents}.waybills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE {documents}.waybills_id_seq OWNED BY {documents}.waybills.id;
CREATE TABLE {documents}.waybills_items (
    id bigint NOT NULL,
    product_id uuid NOT NULL,
    amount double precision NOT NULL,
    waybill_id bigint NOT NULL
);
CREATE SEQUENCE {documents}.waybills_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE {documents}.waybills_items_id_seq OWNED BY {documents}.waybills_items.id;
CREATE TABLE {documents}.writeoffs (
    id bigint NOT NULL,
    comment text,
    status character varying(16) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint NOT NULL,
    processed_by_id bigint,
    store_id uuid NOT NULL,
    reason_id character varying(128),
    processed_at timestamp with time zone,
    submission_state character varying(16) NOT NULL,
    version integer NOT NULL,
    CONSTRAINT writeoffs_version_check CHECK ((version >= 0))
);
CREATE SEQUENCE {documents}.writeoffs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE {documents}.writeoffs_id_seq OWNED BY {documents}.writeoffs.id;
CREATE TABLE {documents}.writeoffs_items (
    id bigint NOT NULL,
    product_id uuid NOT NULL,
    amount double precision NOT NULL,
    writeoff_id bigint NOT NULL
);
CREATE SEQUENCE {documents}.writeoffs_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE {documents}.writeoffs_items_id_seq OWNED BY {documents}.writeoffs_items.id;
CREATE TABLE {documents}.writeoffs_reasons (
    id bigint NOT NULL,
    name character varying(128) NOT NULL,
    account_id uuid
);
CREATE SEQUENCE {documents}.writeoffs_reasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE {documents}.writeoffs_reasons_id_seq OWNED BY {documents}.writeoffs_reasons.id;
ALTER TABLE ONLY {documents}.authentication_user ALTER COLUMN id SET DEFAULT nextval('{documents}.authentication_user_id_seq'::regclass);
ALTER TABLE ONLY {documents}.waybills ALTER COLUMN id SET DEFAULT nextval('{documents}.waybills_id_seq'::regclass);
ALTER TABLE ONLY {documents}.waybills_items ALTER COLUMN id SET DEFAULT nextval('{documents}.waybills_items_id_seq'::regclass);
ALTER TABLE ONLY {documents}.writeoffs ALTER COLUMN id SET DEFAULT nextval('{documents}.writeoffs_id_seq'::regclass);
ALTER TABLE ONLY {documents}.writeoffs_items ALTER COLUMN id SET DEFAULT nextval('{documents}.writeoffs_items_id_seq'::regclass);
ALTER TABLE ONLY {documents}.writeoffs_reasons ALTER COLUMN id SET DEFAULT nextval('{documents}.writeoffs_reasons_id_seq'::regclass);
ALTER TABLE ONLY {documents}.authentication_user
    ADD CONSTRAINT authentication_user_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.authentication_user
    ADD CONSTRAINT authentication_user_telegram_id_key UNIQUE (telegram_id);
ALTER TABLE ONLY {documents}.authentication_user
    ADD CONSTRAINT authentication_user_username_key UNIQUE (username);
ALTER TABLE ONLY {documents}.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (name);
ALTER TABLE ONLY {documents}.portal_documents_grant
    ADD CONSTRAINT documents_unique_grant UNIQUE (user_id, kind, store_id);
ALTER TABLE ONLY {documents}.portal_documents_notification
    ADD CONSTRAINT documents_unique_notification UNIQUE (kind, document_id, version, recipient_id);
ALTER TABLE ONLY {documents}.portal_documents_accessevent
    ADD CONSTRAINT portal_documents_accessevent_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.portal_documents_event
    ADD CONSTRAINT portal_documents_event_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.portal_documents_grant
    ADD CONSTRAINT portal_documents_grant_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.portal_documents_notification
    ADD CONSTRAINT portal_documents_notification_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.portal_documents_operation
    ADD CONSTRAINT portal_documents_operation_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.portal_documents_userlink
    ADD CONSTRAINT portal_documents_userlink_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.portal_documents_userlink
    ADD CONSTRAINT portal_documents_userlink_supabase_id_key UNIQUE (supabase_id);
ALTER TABLE ONLY {documents}.portal_documents_userlink
    ADD CONSTRAINT portal_documents_userlink_user_id_key UNIQUE (user_id);
ALTER TABLE ONLY {documents}.stores
    ADD CONSTRAINT stores_name_key UNIQUE (name);
ALTER TABLE ONLY {documents}.stores
    ADD CONSTRAINT stores_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.waybills_items
    ADD CONSTRAINT waybills_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.waybills
    ADD CONSTRAINT waybills_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.writeoffs_items
    ADD CONSTRAINT writeoffs_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.writeoffs
    ADD CONSTRAINT writeoffs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY {documents}.writeoffs_reasons
    ADD CONSTRAINT writeoffs_reasons_name_key UNIQUE (name);
ALTER TABLE ONLY {documents}.writeoffs_reasons
    ADD CONSTRAINT writeoffs_reasons_pkey PRIMARY KEY (id);
CREATE INDEX authenticat_departm_702e3a_idx ON {documents}.authentication_user USING btree (department_id, is_active);
CREATE INDEX authenticat_telegra_6abf48_idx ON {documents}.authentication_user USING btree (telegram_id);
CREATE INDEX authentication_user_department_id_dd2b59c0 ON {documents}.authentication_user USING btree (department_id);
CREATE INDEX authentication_user_department_id_dd2b59c0_like ON {documents}.authentication_user USING btree (department_id varchar_pattern_ops);
CREATE INDEX authentication_user_username_a09a089e_like ON {documents}.authentication_user USING btree (username varchar_pattern_ops);
CREATE INDEX departments_name_42385b2a_like ON {documents}.departments USING btree (name varchar_pattern_ops);
CREATE INDEX portal_docu_kind_455a94_idx ON {documents}.portal_documents_event USING btree (kind, document_id, id);
CREATE INDEX portal_documents_accessevent_user_id_51dc6f5c ON {documents}.portal_documents_accessevent USING btree (user_id);
CREATE INDEX portal_documents_event_actor_id_a611e7fd ON {documents}.portal_documents_event USING btree (actor_id);
CREATE INDEX portal_documents_grant_store_id_9df41bce ON {documents}.portal_documents_grant USING btree (store_id);
CREATE INDEX portal_documents_grant_user_id_9a7f3130 ON {documents}.portal_documents_grant USING btree (user_id);
CREATE INDEX portal_documents_notification_recipient_id_79aa7ef3 ON {documents}.portal_documents_notification USING btree (recipient_id);
CREATE INDEX portal_documents_operation_actor_id_edcf2817 ON {documents}.portal_documents_operation USING btree (actor_id);
CREATE INDEX stores_name_08426353_like ON {documents}.stores USING btree (name varchar_pattern_ops);
CREATE INDEX waybills_counteragent_id_71b16021 ON {documents}.waybills USING btree (counteragent_id);
CREATE INDEX waybills_created_by_id_869b29bc ON {documents}.waybills USING btree (created_by_id);
CREATE INDEX waybills_created_e91537_idx ON {documents}.waybills USING btree (created_by_id, created_at);
CREATE INDEX waybills_it_product_bc5bf5_idx ON {documents}.waybills_items USING btree (product_id, amount);
CREATE INDEX waybills_it_waybill_974cd4_idx ON {documents}.waybills_items USING btree (waybill_id, product_id);
CREATE INDEX waybills_items_product_id_86875fad ON {documents}.waybills_items USING btree (product_id);
CREATE INDEX waybills_items_waybill_id_84a13900 ON {documents}.waybills_items USING btree (waybill_id);
CREATE INDEX waybills_process_a3f5d3_idx ON {documents}.waybills USING btree (processed_by_id, processed_at);
CREATE INDEX waybills_received_by_id_5a51aa60 ON {documents}.waybills USING btree (processed_by_id);
CREATE INDEX waybills_status_5e00e2_idx ON {documents}.waybills USING btree (status, created_at);
CREATE INDEX waybills_store_i_8340ef_idx ON {documents}.waybills USING btree (store_id, counteragent_id);
CREATE INDEX waybills_store_id_60c77af9 ON {documents}.waybills USING btree (store_id);
CREATE INDEX writeoffs_created_by_id_1f6dca04 ON {documents}.writeoffs USING btree (created_by_id);
CREATE INDEX writeoffs_i_product_20fed3_idx ON {documents}.writeoffs_items USING btree (product_id, amount);
CREATE INDEX writeoffs_i_writeof_39d540_idx ON {documents}.writeoffs_items USING btree (writeoff_id, product_id);
CREATE INDEX writeoffs_items_product_id_74275bb1 ON {documents}.writeoffs_items USING btree (product_id);
CREATE INDEX writeoffs_items_writeoff_id_4b826454 ON {documents}.writeoffs_items USING btree (writeoff_id);
CREATE INDEX writeoffs_process_866727_idx ON {documents}.writeoffs USING btree (processed_by_id, processed_at);
CREATE INDEX writeoffs_reason_id_ca8d5b1b ON {documents}.writeoffs USING btree (reason_id);
CREATE INDEX writeoffs_reason_id_ca8d5b1b_like ON {documents}.writeoffs USING btree (reason_id varchar_pattern_ops);
CREATE INDEX writeoffs_reasons_name_955fbab2_like ON {documents}.writeoffs_reasons USING btree (name varchar_pattern_ops);
CREATE INDEX writeoffs_received_by_id_ac598067 ON {documents}.writeoffs USING btree (processed_by_id);
CREATE INDEX writeoffs_status_58d7bf_idx ON {documents}.writeoffs USING btree (status, created_at);
CREATE INDEX writeoffs_store_i_4f9645_idx ON {documents}.writeoffs USING btree (store_id, created_by_id);
CREATE INDEX writeoffs_store_id_19234a5e ON {documents}.writeoffs USING btree (store_id);
ALTER TABLE ONLY {documents}.authentication_user
    ADD CONSTRAINT authentication_user_department_id_dd2b59c0_fk_departments_name FOREIGN KEY (department_id) REFERENCES {documents}.departments(name) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.portal_documents_accessevent
    ADD CONSTRAINT portal_documents_acc_user_id_51dc6f5c_fk_authentic FOREIGN KEY (user_id) REFERENCES {documents}.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.portal_documents_event
    ADD CONSTRAINT portal_documents_eve_actor_id_a611e7fd_fk_authentic FOREIGN KEY (actor_id) REFERENCES {documents}.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.portal_documents_grant
    ADD CONSTRAINT portal_documents_gra_user_id_9a7f3130_fk_authentic FOREIGN KEY (user_id) REFERENCES {documents}.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.portal_documents_grant
    ADD CONSTRAINT portal_documents_grant_store_id_9df41bce_fk_stores_id FOREIGN KEY (store_id) REFERENCES {documents}.stores(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.portal_documents_notification
    ADD CONSTRAINT portal_documents_not_recipient_id_79aa7ef3_fk_authentic FOREIGN KEY (recipient_id) REFERENCES {documents}.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.portal_documents_operation
    ADD CONSTRAINT portal_documents_ope_actor_id_edcf2817_fk_authentic FOREIGN KEY (actor_id) REFERENCES {documents}.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.portal_documents_userlink
    ADD CONSTRAINT portal_documents_use_user_id_39dbb886_fk_authentic FOREIGN KEY (user_id) REFERENCES {documents}.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.waybills
    ADD CONSTRAINT waybills_counteragent_id_71b16021_fk FOREIGN KEY (counteragent_id) REFERENCES {documents}.stores(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.waybills
    ADD CONSTRAINT waybills_created_by_id_869b29bc_fk_authentication_user_id FOREIGN KEY (created_by_id) REFERENCES {documents}.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.waybills_items
    ADD CONSTRAINT waybills_items_waybill_id_84a13900_fk_waybills_id FOREIGN KEY (waybill_id) REFERENCES {documents}.waybills(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.waybills
    ADD CONSTRAINT waybills_processed_by_id_70a6d3be_fk_authentication_user_id FOREIGN KEY (processed_by_id) REFERENCES {documents}.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.waybills
    ADD CONSTRAINT waybills_store_id_60c77af9_fk FOREIGN KEY (store_id) REFERENCES {documents}.stores(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.writeoffs
    ADD CONSTRAINT writeoffs_created_by_id_1f6dca04_fk_authentication_user_id FOREIGN KEY (created_by_id) REFERENCES {documents}.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.writeoffs_items
    ADD CONSTRAINT writeoffs_items_writeoff_id_4b826454_fk_writeoffs_id FOREIGN KEY (writeoff_id) REFERENCES {documents}.writeoffs(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.writeoffs
    ADD CONSTRAINT writeoffs_processed_by_id_bf32f553_fk_authentication_user_id FOREIGN KEY (processed_by_id) REFERENCES {documents}.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.writeoffs
    ADD CONSTRAINT writeoffs_reason_id_ca8d5b1b_fk_writeoffs_reasons_name FOREIGN KEY (reason_id) REFERENCES {documents}.writeoffs_reasons(name) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY {documents}.writeoffs
    ADD CONSTRAINT writeoffs_store_id_19234a5e_fk FOREIGN KEY (store_id) REFERENCES {documents}.stores(id) DEFERRABLE INITIALLY DEFERRED;

GRANT SELECT,INSERT,UPDATE ON {documents}.authentication_user,
 {documents}.departments,{documents}.stores,
 {documents}.waybills,{documents}.writeoffs,
 {documents}.writeoffs_reasons,{documents}.portal_documents_userlink,
 {documents}.portal_documents_notification,{documents}.portal_documents_operation TO {runtime_role};
GRANT SELECT,INSERT,UPDATE,DELETE ON {documents}.waybills_items,
 {documents}.writeoffs_items,{documents}.portal_documents_grant TO {runtime_role};
GRANT SELECT,INSERT ON {documents}.portal_documents_event,
 {documents}.portal_documents_accessevent TO {runtime_role};
GRANT SELECT ON {documents}.portal_access TO {runtime_role};
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA {documents} TO {runtime_role};
