CREATE SCHEMA chaika_iiko_documents;
--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- transaction_timeout is left at its default for PostgreSQL 16/17 test compatibility.
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: authentication_user; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.authentication_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    telegram_id bigint,
    department_id character varying(128)
);


--
-- Name: authentication_user_id_seq; Type: SEQUENCE; Schema: chaika_iiko_documents; Owner: -
--

CREATE SEQUENCE chaika_iiko_documents.authentication_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: authentication_user_id_seq; Type: SEQUENCE OWNED BY; Schema: chaika_iiko_documents; Owner: -
--

ALTER SEQUENCE chaika_iiko_documents.authentication_user_id_seq OWNED BY chaika_iiko_documents.authentication_user.id;


--
-- Name: departments; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.departments (
    name character varying(128) NOT NULL,
    iiko_id uuid,
    iiko_name character varying(128)
);


--
-- Name: portal_documents_accessevent; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.portal_documents_accessevent (
    id bigint NOT NULL,
    actor_supabase_id uuid NOT NULL,
    revision integer NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT portal_documents_accessevent_revision_check CHECK ((revision >= 0))
);


--
-- Name: portal_documents_accessevent_id_seq; Type: SEQUENCE; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE chaika_iiko_documents.portal_documents_accessevent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chaika_iiko_documents.portal_documents_accessevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_documents_event; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.portal_documents_event (
    id bigint NOT NULL,
    kind character varying(8) NOT NULL,
    document_id bigint NOT NULL,
    version integer NOT NULL,
    action character varying(32) NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    actor_id bigint NOT NULL,
    CONSTRAINT portal_documents_event_version_check CHECK ((version >= 0))
);


--
-- Name: portal_documents_event_id_seq; Type: SEQUENCE; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE chaika_iiko_documents.portal_documents_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chaika_iiko_documents.portal_documents_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_documents_grant; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.portal_documents_grant (
    id bigint NOT NULL,
    kind character varying(8) NOT NULL,
    actions jsonb NOT NULL,
    store_id uuid NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: portal_documents_grant_id_seq; Type: SEQUENCE; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE chaika_iiko_documents.portal_documents_grant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chaika_iiko_documents.portal_documents_grant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_documents_notification; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.portal_documents_notification (
    id bigint NOT NULL,
    kind character varying(8) NOT NULL,
    document_id bigint NOT NULL,
    version integer NOT NULL,
    state character varying(16) NOT NULL,
    attempts integer NOT NULL,
    message_id bigint,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    recipient_id bigint NOT NULL,
    CONSTRAINT portal_documents_notification_attempts_check CHECK ((attempts >= 0)),
    CONSTRAINT portal_documents_notification_version_check CHECK ((version >= 0))
);


--
-- Name: portal_documents_notification_id_seq; Type: SEQUENCE; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE chaika_iiko_documents.portal_documents_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chaika_iiko_documents.portal_documents_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_documents_operation; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.portal_documents_operation (
    id uuid NOT NULL,
    kind character varying(8) NOT NULL,
    document_id bigint,
    action character varying(16) NOT NULL,
    fingerprint character varying(64) NOT NULL,
    state character varying(16) NOT NULL,
    result jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    actor_id bigint NOT NULL
);


--
-- Name: portal_documents_userlink; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.portal_documents_userlink (
    id bigint NOT NULL,
    supabase_id uuid,
    revision integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT portal_documents_userlink_revision_check CHECK ((revision >= 0))
);


--
-- Name: portal_documents_userlink_id_seq; Type: SEQUENCE; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE chaika_iiko_documents.portal_documents_userlink ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chaika_iiko_documents.portal_documents_userlink_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stores; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.stores (
    id uuid NOT NULL,
    name character varying(128) NOT NULL
);


--
-- Name: waybills; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.waybills (
    id bigint NOT NULL,
    comment text,
    status character varying(16) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    counteragent_id uuid NOT NULL,
    created_by_id bigint NOT NULL,
    processed_by_id bigint,
    store_id uuid NOT NULL,
    processed_at timestamp with time zone,
    submission_state character varying(16) NOT NULL,
    version integer NOT NULL,
    CONSTRAINT waybills_version_check CHECK ((version >= 0))
);


--
-- Name: waybills_id_seq; Type: SEQUENCE; Schema: chaika_iiko_documents; Owner: -
--

CREATE SEQUENCE chaika_iiko_documents.waybills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: waybills_id_seq; Type: SEQUENCE OWNED BY; Schema: chaika_iiko_documents; Owner: -
--

ALTER SEQUENCE chaika_iiko_documents.waybills_id_seq OWNED BY chaika_iiko_documents.waybills.id;


--
-- Name: waybills_items; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.waybills_items (
    id bigint NOT NULL,
    product_id uuid NOT NULL,
    amount double precision NOT NULL,
    waybill_id bigint NOT NULL
);


--
-- Name: waybills_items_id_seq; Type: SEQUENCE; Schema: chaika_iiko_documents; Owner: -
--

CREATE SEQUENCE chaika_iiko_documents.waybills_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: waybills_items_id_seq; Type: SEQUENCE OWNED BY; Schema: chaika_iiko_documents; Owner: -
--

ALTER SEQUENCE chaika_iiko_documents.waybills_items_id_seq OWNED BY chaika_iiko_documents.waybills_items.id;


--
-- Name: writeoffs; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.writeoffs (
    id bigint NOT NULL,
    comment text,
    status character varying(16) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint NOT NULL,
    processed_by_id bigint,
    store_id uuid NOT NULL,
    reason_id character varying(128),
    processed_at timestamp with time zone,
    submission_state character varying(16) NOT NULL,
    version integer NOT NULL,
    CONSTRAINT writeoffs_version_check CHECK ((version >= 0))
);


--
-- Name: writeoffs_id_seq; Type: SEQUENCE; Schema: chaika_iiko_documents; Owner: -
--

CREATE SEQUENCE chaika_iiko_documents.writeoffs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: writeoffs_id_seq; Type: SEQUENCE OWNED BY; Schema: chaika_iiko_documents; Owner: -
--

ALTER SEQUENCE chaika_iiko_documents.writeoffs_id_seq OWNED BY chaika_iiko_documents.writeoffs.id;


--
-- Name: writeoffs_items; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.writeoffs_items (
    id bigint NOT NULL,
    product_id uuid NOT NULL,
    amount double precision NOT NULL,
    writeoff_id bigint NOT NULL
);


--
-- Name: writeoffs_items_id_seq; Type: SEQUENCE; Schema: chaika_iiko_documents; Owner: -
--

CREATE SEQUENCE chaika_iiko_documents.writeoffs_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: writeoffs_items_id_seq; Type: SEQUENCE OWNED BY; Schema: chaika_iiko_documents; Owner: -
--

ALTER SEQUENCE chaika_iiko_documents.writeoffs_items_id_seq OWNED BY chaika_iiko_documents.writeoffs_items.id;


--
-- Name: writeoffs_reasons; Type: TABLE; Schema: chaika_iiko_documents; Owner: -
--

CREATE TABLE chaika_iiko_documents.writeoffs_reasons (
    id bigint NOT NULL,
    name character varying(128) NOT NULL,
    account_id uuid
);


--
-- Name: writeoffs_reasons_id_seq; Type: SEQUENCE; Schema: chaika_iiko_documents; Owner: -
--

CREATE SEQUENCE chaika_iiko_documents.writeoffs_reasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: writeoffs_reasons_id_seq; Type: SEQUENCE OWNED BY; Schema: chaika_iiko_documents; Owner: -
--

ALTER SEQUENCE chaika_iiko_documents.writeoffs_reasons_id_seq OWNED BY chaika_iiko_documents.writeoffs_reasons.id;


--
-- Name: authentication_user id; Type: DEFAULT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.authentication_user ALTER COLUMN id SET DEFAULT nextval('chaika_iiko_documents.authentication_user_id_seq'::regclass);


--
-- Name: waybills id; Type: DEFAULT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.waybills ALTER COLUMN id SET DEFAULT nextval('chaika_iiko_documents.waybills_id_seq'::regclass);


--
-- Name: waybills_items id; Type: DEFAULT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.waybills_items ALTER COLUMN id SET DEFAULT nextval('chaika_iiko_documents.waybills_items_id_seq'::regclass);


--
-- Name: writeoffs id; Type: DEFAULT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs ALTER COLUMN id SET DEFAULT nextval('chaika_iiko_documents.writeoffs_id_seq'::regclass);


--
-- Name: writeoffs_items id; Type: DEFAULT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs_items ALTER COLUMN id SET DEFAULT nextval('chaika_iiko_documents.writeoffs_items_id_seq'::regclass);


--
-- Name: writeoffs_reasons id; Type: DEFAULT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs_reasons ALTER COLUMN id SET DEFAULT nextval('chaika_iiko_documents.writeoffs_reasons_id_seq'::regclass);


--
-- Name: authentication_user authentication_user_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.authentication_user
    ADD CONSTRAINT authentication_user_pkey PRIMARY KEY (id);


--
-- Name: authentication_user authentication_user_telegram_id_key; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.authentication_user
    ADD CONSTRAINT authentication_user_telegram_id_key UNIQUE (telegram_id);


--
-- Name: authentication_user authentication_user_username_key; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.authentication_user
    ADD CONSTRAINT authentication_user_username_key UNIQUE (username);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (name);


--
-- Name: portal_documents_grant documents_unique_grant; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_grant
    ADD CONSTRAINT documents_unique_grant UNIQUE (user_id, kind, store_id);


--
-- Name: portal_documents_notification documents_unique_notification; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_notification
    ADD CONSTRAINT documents_unique_notification UNIQUE (kind, document_id, version, recipient_id);


--
-- Name: portal_documents_accessevent portal_documents_accessevent_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_accessevent
    ADD CONSTRAINT portal_documents_accessevent_pkey PRIMARY KEY (id);


--
-- Name: portal_documents_event portal_documents_event_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_event
    ADD CONSTRAINT portal_documents_event_pkey PRIMARY KEY (id);


--
-- Name: portal_documents_grant portal_documents_grant_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_grant
    ADD CONSTRAINT portal_documents_grant_pkey PRIMARY KEY (id);


--
-- Name: portal_documents_notification portal_documents_notification_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_notification
    ADD CONSTRAINT portal_documents_notification_pkey PRIMARY KEY (id);


--
-- Name: portal_documents_operation portal_documents_operation_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_operation
    ADD CONSTRAINT portal_documents_operation_pkey PRIMARY KEY (id);


--
-- Name: portal_documents_userlink portal_documents_userlink_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_userlink
    ADD CONSTRAINT portal_documents_userlink_pkey PRIMARY KEY (id);


--
-- Name: portal_documents_userlink portal_documents_userlink_supabase_id_key; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_userlink
    ADD CONSTRAINT portal_documents_userlink_supabase_id_key UNIQUE (supabase_id);


--
-- Name: portal_documents_userlink portal_documents_userlink_user_id_key; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_userlink
    ADD CONSTRAINT portal_documents_userlink_user_id_key UNIQUE (user_id);


--
-- Name: stores stores_name_key; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.stores
    ADD CONSTRAINT stores_name_key UNIQUE (name);


--
-- Name: stores stores_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.stores
    ADD CONSTRAINT stores_pkey PRIMARY KEY (id);


--
-- Name: waybills_items waybills_items_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.waybills_items
    ADD CONSTRAINT waybills_items_pkey PRIMARY KEY (id);


--
-- Name: waybills waybills_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.waybills
    ADD CONSTRAINT waybills_pkey PRIMARY KEY (id);


--
-- Name: writeoffs_items writeoffs_items_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs_items
    ADD CONSTRAINT writeoffs_items_pkey PRIMARY KEY (id);


--
-- Name: writeoffs writeoffs_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs
    ADD CONSTRAINT writeoffs_pkey PRIMARY KEY (id);


--
-- Name: writeoffs_reasons writeoffs_reasons_name_key; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs_reasons
    ADD CONSTRAINT writeoffs_reasons_name_key UNIQUE (name);


--
-- Name: writeoffs_reasons writeoffs_reasons_pkey; Type: CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs_reasons
    ADD CONSTRAINT writeoffs_reasons_pkey PRIMARY KEY (id);


--
-- Name: authenticat_departm_702e3a_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX authenticat_departm_702e3a_idx ON chaika_iiko_documents.authentication_user USING btree (department_id, is_active);


--
-- Name: authenticat_telegra_6abf48_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX authenticat_telegra_6abf48_idx ON chaika_iiko_documents.authentication_user USING btree (telegram_id);


--
-- Name: authentication_user_department_id_dd2b59c0; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX authentication_user_department_id_dd2b59c0 ON chaika_iiko_documents.authentication_user USING btree (department_id);


--
-- Name: authentication_user_department_id_dd2b59c0_like; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX authentication_user_department_id_dd2b59c0_like ON chaika_iiko_documents.authentication_user USING btree (department_id varchar_pattern_ops);


--
-- Name: authentication_user_username_a09a089e_like; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX authentication_user_username_a09a089e_like ON chaika_iiko_documents.authentication_user USING btree (username varchar_pattern_ops);


--
-- Name: departments_name_42385b2a_like; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX departments_name_42385b2a_like ON chaika_iiko_documents.departments USING btree (name varchar_pattern_ops);


--
-- Name: portal_docu_kind_455a94_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX portal_docu_kind_455a94_idx ON chaika_iiko_documents.portal_documents_event USING btree (kind, document_id, id);


--
-- Name: portal_documents_accessevent_user_id_51dc6f5c; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX portal_documents_accessevent_user_id_51dc6f5c ON chaika_iiko_documents.portal_documents_accessevent USING btree (user_id);


--
-- Name: portal_documents_event_actor_id_a611e7fd; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX portal_documents_event_actor_id_a611e7fd ON chaika_iiko_documents.portal_documents_event USING btree (actor_id);


--
-- Name: portal_documents_grant_store_id_9df41bce; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX portal_documents_grant_store_id_9df41bce ON chaika_iiko_documents.portal_documents_grant USING btree (store_id);


--
-- Name: portal_documents_grant_user_id_9a7f3130; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX portal_documents_grant_user_id_9a7f3130 ON chaika_iiko_documents.portal_documents_grant USING btree (user_id);


--
-- Name: portal_documents_notification_recipient_id_79aa7ef3; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX portal_documents_notification_recipient_id_79aa7ef3 ON chaika_iiko_documents.portal_documents_notification USING btree (recipient_id);


--
-- Name: portal_documents_operation_actor_id_edcf2817; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX portal_documents_operation_actor_id_edcf2817 ON chaika_iiko_documents.portal_documents_operation USING btree (actor_id);


--
-- Name: stores_name_08426353_like; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX stores_name_08426353_like ON chaika_iiko_documents.stores USING btree (name varchar_pattern_ops);


--
-- Name: waybills_counteragent_id_71b16021; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_counteragent_id_71b16021 ON chaika_iiko_documents.waybills USING btree (counteragent_id);


--
-- Name: waybills_created_by_id_869b29bc; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_created_by_id_869b29bc ON chaika_iiko_documents.waybills USING btree (created_by_id);


--
-- Name: waybills_created_e91537_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_created_e91537_idx ON chaika_iiko_documents.waybills USING btree (created_by_id, created_at);


--
-- Name: waybills_it_product_bc5bf5_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_it_product_bc5bf5_idx ON chaika_iiko_documents.waybills_items USING btree (product_id, amount);


--
-- Name: waybills_it_waybill_974cd4_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_it_waybill_974cd4_idx ON chaika_iiko_documents.waybills_items USING btree (waybill_id, product_id);


--
-- Name: waybills_items_product_id_86875fad; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_items_product_id_86875fad ON chaika_iiko_documents.waybills_items USING btree (product_id);


--
-- Name: waybills_items_waybill_id_84a13900; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_items_waybill_id_84a13900 ON chaika_iiko_documents.waybills_items USING btree (waybill_id);


--
-- Name: waybills_process_a3f5d3_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_process_a3f5d3_idx ON chaika_iiko_documents.waybills USING btree (processed_by_id, processed_at);


--
-- Name: waybills_received_by_id_5a51aa60; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_received_by_id_5a51aa60 ON chaika_iiko_documents.waybills USING btree (processed_by_id);


--
-- Name: waybills_status_5e00e2_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_status_5e00e2_idx ON chaika_iiko_documents.waybills USING btree (status, created_at);


--
-- Name: waybills_store_i_8340ef_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_store_i_8340ef_idx ON chaika_iiko_documents.waybills USING btree (store_id, counteragent_id);


--
-- Name: waybills_store_id_60c77af9; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX waybills_store_id_60c77af9 ON chaika_iiko_documents.waybills USING btree (store_id);


--
-- Name: writeoffs_created_by_id_1f6dca04; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_created_by_id_1f6dca04 ON chaika_iiko_documents.writeoffs USING btree (created_by_id);


--
-- Name: writeoffs_i_product_20fed3_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_i_product_20fed3_idx ON chaika_iiko_documents.writeoffs_items USING btree (product_id, amount);


--
-- Name: writeoffs_i_writeof_39d540_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_i_writeof_39d540_idx ON chaika_iiko_documents.writeoffs_items USING btree (writeoff_id, product_id);


--
-- Name: writeoffs_items_product_id_74275bb1; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_items_product_id_74275bb1 ON chaika_iiko_documents.writeoffs_items USING btree (product_id);


--
-- Name: writeoffs_items_writeoff_id_4b826454; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_items_writeoff_id_4b826454 ON chaika_iiko_documents.writeoffs_items USING btree (writeoff_id);


--
-- Name: writeoffs_process_866727_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_process_866727_idx ON chaika_iiko_documents.writeoffs USING btree (processed_by_id, processed_at);


--
-- Name: writeoffs_reason_id_ca8d5b1b; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_reason_id_ca8d5b1b ON chaika_iiko_documents.writeoffs USING btree (reason_id);


--
-- Name: writeoffs_reason_id_ca8d5b1b_like; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_reason_id_ca8d5b1b_like ON chaika_iiko_documents.writeoffs USING btree (reason_id varchar_pattern_ops);


--
-- Name: writeoffs_reasons_name_955fbab2_like; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_reasons_name_955fbab2_like ON chaika_iiko_documents.writeoffs_reasons USING btree (name varchar_pattern_ops);


--
-- Name: writeoffs_received_by_id_ac598067; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_received_by_id_ac598067 ON chaika_iiko_documents.writeoffs USING btree (processed_by_id);


--
-- Name: writeoffs_status_58d7bf_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_status_58d7bf_idx ON chaika_iiko_documents.writeoffs USING btree (status, created_at);


--
-- Name: writeoffs_store_i_4f9645_idx; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_store_i_4f9645_idx ON chaika_iiko_documents.writeoffs USING btree (store_id, created_by_id);


--
-- Name: writeoffs_store_id_19234a5e; Type: INDEX; Schema: chaika_iiko_documents; Owner: -
--

CREATE INDEX writeoffs_store_id_19234a5e ON chaika_iiko_documents.writeoffs USING btree (store_id);


--
-- Name: authentication_user authentication_user_department_id_dd2b59c0_fk_departments_name; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.authentication_user
    ADD CONSTRAINT authentication_user_department_id_dd2b59c0_fk_departments_name FOREIGN KEY (department_id) REFERENCES chaika_iiko_documents.departments(name) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_documents_accessevent portal_documents_acc_user_id_51dc6f5c_fk_authentic; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_accessevent
    ADD CONSTRAINT portal_documents_acc_user_id_51dc6f5c_fk_authentic FOREIGN KEY (user_id) REFERENCES chaika_iiko_documents.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_documents_event portal_documents_eve_actor_id_a611e7fd_fk_authentic; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_event
    ADD CONSTRAINT portal_documents_eve_actor_id_a611e7fd_fk_authentic FOREIGN KEY (actor_id) REFERENCES chaika_iiko_documents.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_documents_grant portal_documents_gra_user_id_9a7f3130_fk_authentic; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_grant
    ADD CONSTRAINT portal_documents_gra_user_id_9a7f3130_fk_authentic FOREIGN KEY (user_id) REFERENCES chaika_iiko_documents.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_documents_grant portal_documents_grant_store_id_9df41bce_fk_stores_id; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_grant
    ADD CONSTRAINT portal_documents_grant_store_id_9df41bce_fk_stores_id FOREIGN KEY (store_id) REFERENCES chaika_iiko_documents.stores(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_documents_notification portal_documents_not_recipient_id_79aa7ef3_fk_authentic; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_notification
    ADD CONSTRAINT portal_documents_not_recipient_id_79aa7ef3_fk_authentic FOREIGN KEY (recipient_id) REFERENCES chaika_iiko_documents.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_documents_operation portal_documents_ope_actor_id_edcf2817_fk_authentic; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_operation
    ADD CONSTRAINT portal_documents_ope_actor_id_edcf2817_fk_authentic FOREIGN KEY (actor_id) REFERENCES chaika_iiko_documents.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_documents_userlink portal_documents_use_user_id_39dbb886_fk_authentic; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.portal_documents_userlink
    ADD CONSTRAINT portal_documents_use_user_id_39dbb886_fk_authentic FOREIGN KEY (user_id) REFERENCES chaika_iiko_documents.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: waybills waybills_counteragent_id_71b16021_fk; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.waybills
    ADD CONSTRAINT waybills_counteragent_id_71b16021_fk FOREIGN KEY (counteragent_id) REFERENCES chaika_iiko_documents.stores(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: waybills waybills_created_by_id_869b29bc_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.waybills
    ADD CONSTRAINT waybills_created_by_id_869b29bc_fk_authentication_user_id FOREIGN KEY (created_by_id) REFERENCES chaika_iiko_documents.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: waybills_items waybills_items_waybill_id_84a13900_fk_waybills_id; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.waybills_items
    ADD CONSTRAINT waybills_items_waybill_id_84a13900_fk_waybills_id FOREIGN KEY (waybill_id) REFERENCES chaika_iiko_documents.waybills(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: waybills waybills_processed_by_id_70a6d3be_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.waybills
    ADD CONSTRAINT waybills_processed_by_id_70a6d3be_fk_authentication_user_id FOREIGN KEY (processed_by_id) REFERENCES chaika_iiko_documents.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: waybills waybills_store_id_60c77af9_fk; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.waybills
    ADD CONSTRAINT waybills_store_id_60c77af9_fk FOREIGN KEY (store_id) REFERENCES chaika_iiko_documents.stores(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: writeoffs writeoffs_created_by_id_1f6dca04_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs
    ADD CONSTRAINT writeoffs_created_by_id_1f6dca04_fk_authentication_user_id FOREIGN KEY (created_by_id) REFERENCES chaika_iiko_documents.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: writeoffs_items writeoffs_items_writeoff_id_4b826454_fk_writeoffs_id; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs_items
    ADD CONSTRAINT writeoffs_items_writeoff_id_4b826454_fk_writeoffs_id FOREIGN KEY (writeoff_id) REFERENCES chaika_iiko_documents.writeoffs(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: writeoffs writeoffs_processed_by_id_bf32f553_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs
    ADD CONSTRAINT writeoffs_processed_by_id_bf32f553_fk_authentication_user_id FOREIGN KEY (processed_by_id) REFERENCES chaika_iiko_documents.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: writeoffs writeoffs_reason_id_ca8d5b1b_fk_writeoffs_reasons_name; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs
    ADD CONSTRAINT writeoffs_reason_id_ca8d5b1b_fk_writeoffs_reasons_name FOREIGN KEY (reason_id) REFERENCES chaika_iiko_documents.writeoffs_reasons(name) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: writeoffs writeoffs_store_id_19234a5e_fk; Type: FK CONSTRAINT; Schema: chaika_iiko_documents; Owner: -
--

ALTER TABLE ONLY chaika_iiko_documents.writeoffs
    ADD CONSTRAINT writeoffs_store_id_19234a5e_fk FOREIGN KEY (store_id) REFERENCES chaika_iiko_documents.stores(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


CREATE TABLE chaika_iiko_documents.portal_access (id uuid PRIMARY KEY,active boolean,sections jsonb,is_portal_admin boolean);

-- Synthetic equivalent of the read-only shared portal ACL. Missing override
-- retains legacy all mode; selected + NULL store explicitly grants no stores.
CREATE TABLE chaika_iiko_documents.portal_warehouse_scope_test (
 user_id uuid REFERENCES chaika_iiko_documents.portal_access(id) ON DELETE CASCADE,
 warehouse_scope_mode text NOT NULL CHECK(warehouse_scope_mode IN ('all','selected')),
 store_id uuid
);
CREATE SCHEMA IF NOT EXISTS chaika;
CREATE OR REPLACE VIEW chaika.portal_warehouse_access AS
 SELECT p.id AS user_id,coalesce(w.warehouse_scope_mode,'all') AS warehouse_scope_mode,
 'primary'::text AS source_id,w.store_id
 FROM chaika_iiko_documents.portal_access p
 LEFT JOIN chaika_iiko_documents.portal_warehouse_scope_test w ON w.user_id=p.id
 WHERE p.active;
GRANT USAGE ON SCHEMA chaika TO chaika_iiko_app;
GRANT SELECT ON chaika.portal_warehouse_access TO chaika_iiko_app;
